### PR TITLE
Update interp_inc to allow hdf5 >=1.10.9

### PR DESCRIPTION
**Pull request by AlexanderRichert-NOAA**
This PR modifies src/netcdf_io/interp_inc.fd/driver.f90 to allow it to run with hdf5 1.10.9 and later. As of 1.10.9, certain MPI-based hdf5 functions must have the root MPI process (`mype==0`) available in order to run. In the current code, as discovered by @KateFriedman-NOAA, this causes interp_inc.x to hang in the `nf90_inq_varid` function. This PR takes the last (`npes-1`) MPI proc and makes it the command-and-control task instead of proc 0. Tested with Global Workflow on Orion.

### CODE REVIEW

**Comment by AlexanderRichert-NOAA** [comment]
@aerorahul @RussTreadon-NOAA is there someone who can review this?

**Review by aerorahul — COMMENTED** [review]
@AlexanderRichert-NOAA 
I am not familiar with this program, but I can provide a brief review based on what I understand.

I have 2 sets of comments:
1.a. Is it necessary to change the `if(mype == 0)` for calls to `w3` or `print` statements?  I wouldn't think that would be necessary.
1.b. Is it necessary to change the `rec` to `rec-1`; such as on line 341, because effectively, when `rec=1`, the `nf90_` call on line 344 is performed on `pe=0`.
 2. I can see the changes where netcdf calls are performed on `mype == 0` to be made on `mype = npes - 1`.  I am ok with that.  Corresspondingly, the `mpi_send` and `mpi_recv` need to be flipped.  I understand this as well.

**Comment by AlexanderRichert-NOAA** [comment]
> 1.a. Is it necessary to change the `if(mype == 0)` for calls to `w3` or `print` statements? I wouldn't think that would be necessary.
> 1.b. Is it necessary to change the `rec` to `rec-1`; such as on line 341, because effectively, when `rec=1`, the `nf90_` call on line 344 is performed on `pe=0`.
> 2. I can see the changes where netcdf calls are performed on `mype == 0` to be made on `mype = npes - 1`.  I am ok with that.  Corresspondingly, the `mpi_send` and `mpi_recv` need to be flipped.  I understand this as well.

1.a. Basically yes, because otherwise a variable set somewhere above in the program won't be populated on the correct process. I haven't done an inventory of every single `if (mype .eq. npes-1)` but I think the simplest and safest thing is to make them uniform.
1.b. Yes, this is intentional. For the 10 procs that this program runs with, the idea is to get all of the netcdf in that big loop on 0-8, instead of 1-9. Before I changed `rec` to `rec-1`, it was not working.
2. I'm not sure what you mean about `mpi_recv` and `mpi_send` needing to be flipped? In any case I'm 99% sure that it's correct as it is (npes-1 is the C&C proc, so it should be receiving, i.e., it's precisely taking over the role that mype==0 was playing before).

**Review by aerorahul — DISMISSED** [review]
The changes seem reasonable to me. 
Are these changes backward compatible with current version of hdf5 used?

**Comment by AlexanderRichert-NOAA** [comment]
Yes, it runs successfully with hpc-stack/intel 2018/hdf5@1.10.6 per the current modulefiles.

**Review by CoryMartin-NOAA — DISMISSED** [review]

**Comment by AlexanderRichert-NOAA** [comment]
@aerorahul @CoryMartin-NOAA had to make some CI changes, everything appears to be working now.

**Review by CoryMartin-NOAA — APPROVED** [review]

**Comment by AlexanderRichert-NOAA** [comment]
@CoryMartin-NOAA @aerorahul does one of you have the ability to merge this?

**Pull request merged**
