### PR TITLE
Updates for Rocky 8.

### PR DESCRIPTION
**Pull request by HenryRWinterbottom**
Updates for RDHPCS Hera Rocky-8 upgrade.

### CODE REVIEW

**Review by aerorahul — DISMISSED** [review]
looks good.

**Review by RussTreadon-NOAA — DISMISSED** [review]
Looks good to me.  The same change was made in GSI PR [#715](https://github.com/NOAA-EMC/GSI/pull/715).

Approve.

**Review by DavidHuber-NOAA — APPROVED** [review]
The Intel changes look good, but the GNU compilers should also be updated.  That can be handled in a separate PR if needed.  Approve.

**Comment by DavidHuber-NOAA** [comment]
@HenryWinterbottom-NOAA Note, if you change the GNU module file, also delete line 6:
https://github.com/NOAA-EMC/GSI-utils/blob/55abe588252ec6f39047d54a14727cf59f7f6688/modulefiles/gsiutils_hera.gnu.lua#L6
The openmpi module is now in the standard stack and does not require an external use statement.

**Review by aerorahul — APPROVED** [review]
looks good.

**Pull request merged**
