### PR TITLE
Build gsi_utils on Gaea-C5

### PR DESCRIPTION
**Pull request by DavidBurrows-NCO**
Update module files to build on Gaea-C5

Ref #38 
Cross Ref NOAA-EMC/global-workflow/issues/2535

### CODE REVIEW

**Comment by DavidBurrows-NCO** [comment]
Hi @aerorahul. I can't seem to find the button to request a review, so I figured I would mention you here. I see you reviewed Wei's build for AWS.

**Review by aerorahul — APPROVED** [review]
looks good.
thanks!

**Comment by DavidBurrows-NCO** [comment]
Morning @aerorahul. Is there anything else I need to do with this one? It looks like the workflows are waiting approval...Thanks.

**Comment by aerorahul** [comment]
> Morning @aerorahul. Is there anything else I need to do with this one? It looks like the workflows are waiting approval...Thanks.

I just merged in the latest develop into your PR branch.
It is running the workflows now and once it succeeds, I will merge this PR.
Apologies for the delay. I am not a CM for this repo, but I do help out when needed.

**Comment by DavidBurrows-NCO** [comment]
Great. Thanks @aerorahul. I would have been more on top of this but was out sick a few days last week and everything piled up!

**Pull request merged**
