### PR TITLE
Remove two deprecated utilities

### LINKED ISSUE #24: Remove (some) deprecated utilities.
Specifically:
Radiance_utilities/diag2grads
global_angupdate

These 2 (atleast) have dead links to fortran code from the GSI.  These two are currently not built (or buildable) and therefore are not used (that is an assumption on my part unless someone has a secret way of building them that is not in this repository).

Suggesting to remove them from `develop` (They will always be in the repository history).

@RussTreadon-NOAA @ADCollard @dtkleist 
Please let me know if there are concerns regarding this by Jan 1, 2024.

### PR DESCRIPTION
**Pull request by aerorahul**
Fixes #24 
(can wait till 1/1/2024 to get feedback and comments)

### CODE REVIEW

**Review by RussTreadon-NOAA — COMMENTED** [review]
I am not aware of `global_angupdate` being used anywhere.  The same comment applies to `diag2grads`.   Let's cross check with @EdwardSafford-NOAA.

**Review by ADCollard — APPROVED** [review]
I do not believe either of these utilities are used any more.  It is possible that there are still people plotting radiance diag files with GrADS but this particular utility does not appear to support ncdiag files, so it should be OK to remove.

**Review by RussTreadon-NOAA — APPROVED** [review]
If any developer needs `diag2grads` or `global_angupdate`, they can recover either from previous GSI-utils hashes.

Approve.

**Comment by aerorahul** [comment]
@ADCollard @RussTreadon-NOAA 
Thank you for your approval.
Please feel free to merge whenever you get a chance.

**Comment by RussTreadon-NOAA** [comment]
Thanks @aerorahul , you, too, are also free to merge this PR into `develop`.  We don't have a CM for GSI-utils.

**Pull request merged**
