### PR TITLE
Add handling to calculate analysis and interplate increments for number

### PR DESCRIPTION
**Pull request by emilyhcliu**
The fv3 model uses Thompson scheme and therefore, there are two prognostic cloud-related variables:
- number concentration of cloud ice (ni)
- number concentration of rain (nr)

The GSI interface has updated to read in these two extra variables and  therefore, the gdas.t${cyc}.atmf{fhr}.nc files have the following two additional fields: nccice (ni) and nconrd (nr)

```
        float nccice(time, pfull, grid_yt, grid_xt) ;
                nccice:_FillValue = 9.99e+20f ;
                nccice:cell_methods = "time: point" ;
                nccice:long_name = "cloud ice water number concentration" ;
                nccice:missing_value = 9.99e+20f ;
                nccice:output_file = "atm" ;
                nccice:units = "/kg" ;
        float nconrd(time, pfull, grid_yt, grid_xt) ;
                nconrd:_FillValue = 9.99e+20f ;
                nconrd:cell_methods = "time: point" ;
                nconrd:long_name = "rain number concentration" ;
                nconrd:missing_value = 9.99e+20f ;
                nconrd:output_file = "atm" ;
                nconrd:units = "/kg" ;
```
Currently, the `atmanl` file includes `nccice` and `nconrd` but they are missing values. 
For consistency, the related output gdas.t${cyc}.atmanl.nc should have valid values for nccice (ni) and nconrd (nr).

The number concentration of ice and rain are not control variables, and therefore, there are no increments associated with them.  But the output atmanl should have valid values for them copied from the input guess fields.  

In addition, the precipitation variables (rain, snow and graupel) are added to the interpolation routine for resolution change.  Currently, the cloud and precipitation increments are zero.  This update is to prepare for future testing when we want to pass the cloud and precipitation increments back to the model.  

This PR has a related PR in [global-workflow #2648](https://github.com/NOAA-EMC/global-workflow/pull/2648)
The number MPI declared need to be increased from 10 to 13 in the python script which runs this utility

### CODE REVIEW

**Comment by CoryMartin-NOAA** [comment]
@emilyhcliu is this ready for review and testing? I have a similar PR ready for aerosols

**Review by CoryMartin-NOAA — DISMISSED** [review]
Did not test but changes look good

**Comment by emilyhcliu** [comment]
@CoryMartin-NOAA These changes are tested in GDAS parallel experiments.  They worked OK. 
One thing to know is that the computation resource needs to increase slightly for this step.

**Comment by CoryMartin-NOAA** [comment]
@emilyhcliu just for the interp_inc right, not for the calc_analysis?

**Comment by emilyhcliu** [comment]
> @emilyhcliu just for the interp_inc right, not for the calc_analysis?

@CoryMartin-NOAA Correct!!  It is the execution of `interp_inc.x`

**Review by CoryMartin-NOAA — APPROVED** [review]

**Review by RussTreadon-NOAA — APPROVED** [review]
Approved.  By how much does the `interp_inc.x` wall time increase with these changes?

**Comment by CoryMartin-NOAA** [comment]
@emilyhcliu may be able to answer that. I suspect not by much because it's largely parallelized and the workflow was updated to give it more PEs (it assumes 1 PE per variable)

**Comment by emilyhcliu** [comment]
> @emilyhcliu may be able to answer that. I suspect not by much because it's largely parallelized and the workflow was updated to give it more PEs (it assumes 1 PE per variable)

Here is the original allocation: (the run failed constantly)
```
        <jobname><cyclestr>v17allskyens_gdasanalcalc_@H</cyclestr></jobname>
        <account>da-cpu</account>
        <queue>batch</queue>
        <partition>hera</partition>
        <walltime>00:10:00</walltime>
        <nodes>4:ppn:40:tpp=1</nodes>
        <memory>48GB</memory>
        <native>--export=NONE</native>
```

Here is the updated allocation:
```
        <jobname><cyclestr>v17allskyens_gdasanalcalc_@H</cyclestr></jobname>
        <account>da-cpu</account>
        <queue>batch</queue>
        <partition>hera</partition>
        <walltime>00:10:00</walltime>
        <nodes>8:ppn=20:tpp=1</nodes>
        <memory>90GB</memory>
        <native>--export=NONE</native>
```

**Comment by RussTreadon-NOAA** [comment]
Thank you @emilyhcliu .  The specified wall clock limit remains unchanged.  The node count doubled as the ppn was halved along with a larger memory request.  Makes sense since more fields are being processed.

The increased size of the output files may be of greater concern.  This can impact HPSS not only disk space.

Does the updated code work for `imp_physics=8` and `imp_physics=11`?

**Comment by emilyhcliu** [comment]
> Thank you @emilyhcliu . The specified wall clock limit remains unchanged. The node count doubled as the ppn was halved along with a larger memory request. Makes sense since more fields are being processed.
> 
> The increased size of the output files may be of greater concern. This can impact HPSS not only disk space.
> 
> Does the updated code work for `imp_physics=8` and `imp_physics=11`?

@RussTreadon-NOAA The code works for both (imp_physics 8 or 11).

**Comment by RussTreadon-NOAA** [comment]
Great!

**Pull request merged**
