### PR TITLE
Upgrade modules to spack-stack/1.5.1 on non-production machines.

### LINKED ISSUE #18: Use EPIC-managed spack-stack installations for non-production machines
The UFS has migrated to spack-stack/1.4.1 and there is work being done to migrate the GSI to the same (NOAA-EMC/GSI#589) on non-production machines (WCOSS2 is still using Intel/19).  The GSI-utils should also be migrated to use spack-stack.  This will involve a few upgrades at once: Intel 18 to 2021+, hdf5/1.10.6 to 1.14.0, and netcdf/4.7.4 to 4.9.2.  It should be noted that during a port to a NESDIS GCP instance, the only compiler available was Intel 2021.  The GSI utilities ran fine at coarser resolutions, but the EnKF recentering utility sometimes failed at ensemble resolution C192.

I am going to try this in one step to bypass #13 (since hpc-stack is minimally supported) and address #15.  My suggested plan for testing is to run 40 cycles in the global workflow at all available resolutions up to C384/C192 and 4 additional cycles at C768/C384 as it is the only application that makes use of this utility suite.

### PR DESCRIPTION
**Pull request by DavidHuber-NOAA**
This upgrades the modules on non-productions machines to use the local spack-stack installations.  This has been build-tested on Hera (Intel and GNU), Orion, S4, Jet, and WCOSS2.  It has been run-tested on Orion and Hera within global workflow experiments.

In the process, the Cheyenne modulefiles have been removed as that system is being decomissioned and spack-stack/1.5.1 is not available there.

Resolves #18

### CODE REVIEW

**Review by aerorahul — DISMISSED** [review]
looks good to me

**Review by RussTreadon-NOAA — COMMENTED** [review]
We have no CI testing for GSI-utils. This is problematic.  

@DavidHuber-NOAA tested the updated GSI-utils in g-w on Hera and Orion.   The build was tested on WCOSS2 (along with other machines).   Since Dave did not report any anomalies, I assume GSI-utils behaves acceptably when built from spack-stack/1.5.1.

`src/netcdf_io/interp_inc.fd/driver.F90 was updated.  The change is related to ip.  An ip-lib subject matter expert could check this update if we want confirmation that the change is OK.

**Comment by DavidHuber-NOAA** [comment]
@RussTreadon-NOAA I am working on updating the CI for gsi-utils for this PR.  I will submit it shortly.

**Comment by DavidHuber-NOAA** [comment]
Hmm, for some reason, `sudo apt install cmake` is installing version 3.16, which is too old for our purposes.  I will need to read up on how to force a newer version.

**Comment by DavidHuber-NOAA** [comment]
@aerorahul I'm not sure how to get `cmake`/`hdf5`/`MPI` to work together here.  As is, `cmake`, during the `hdf5` build, is unable to find `MPI_C`.  UFS_utils, which I have been using as a template, uses `ubuntu-20.04`, which builds `cmake/3.16`, but that version is too old for at least one of the library builds, so I am currently working with `ubuntu-latest` and this version is unable to find `MPI`.  Any ideas on how to reconcile this?

**Comment by aerorahul** [comment]
> @aerorahul I'm not sure how to get `cmake`/`hdf5`/`MPI` to work together here. As is, `cmake`, during the `hdf5` build, is unable to find `MPI_C`. UFS_utils, which I have been using as a template, uses `ubuntu-20.04`, which builds `cmake/3.16`, but that version is too old for at least one of the library builds, so I am currently working with `ubuntu-latest` and this version is unable to find `MPI`. Any ideas on how to reconcile this?

can you install `cmake` from spack in the `spack.yaml`?

**Review by aerorahul — APPROVED** [review]
LGTM.
Thanks for updating the CI, updating the utilities to newer versions of the libraries and porting to spack-stack.

**Comment by DavidHuber-NOAA** [comment]
@souopgui-redline identified a bug causing a hang on S4.  The netcdf file read in `interp_inc` is opened in parallel mode, but only read serially.  Changing this to open it in serial mode solved the hang.  This has only been tested on S4 so far, but I could run a quick test on Orion as well.

**Comment by DavidHuber-NOAA** [comment]
This also worked on Orion.  I think this is now ready to merge once CI tests complete.

**Review by RussTreadon-NOAA — APPROVED** [review]
Trust your testing @DavidHuber-NOAA  and trust @aerorahul 's review.

Approve.

**Comment by DavidHuber-NOAA** [comment]
All CI tests passed.  I don't think there are any further hurdles and that this is ready to merge.

**Pull request merged**
